# Site settings
title: Wyatt Solutions1
email: wyattleewriting@gmail.com
url: https://wyattsolutions.co
description: "We offer expert technical writing services specializing in case studies with narrative story telling and analytics. We also do API documentation, user manuals, training and onboarding guides, and SaaS product documentation to help companies deliver clear, reliable, and up-to-date content that drives customer success and reduces support costs."
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: wyattsolutions

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0072C6 #80B3FF
  primary-rgb: "0,114,198" #"128,179,255"
  secondary: 002050 #FD6E8A
  secondary-dark: 001833 #A2122F

# Footer settings
footer:
  copyright: Wyatt Solutions Inc.
  location:
  social: Tell us about your unique content strategy, story telling, documentation, training or technical writing needs
  credits: This site was built using open source.
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Serving businesses
  - line: globally

# Credits content
credits: 'This site was custom built by Wyatt Solutions'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
